version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/zweb-builder-backend.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /zweb-builder-backend.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=zweb-builder-backend -f zweb-builder-backend.dockerfile -t zweb-builder-backend .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/zweb-builder-backend.tar zweb-builder-backend
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/zweb-builder-backend.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker tag zweb-builder-backend "zwebsoft/zweb-builder-backend:${CIRCLE_BRANCH}"
            docker push "zwebsoft/zweb-builder-backend:${CIRCLE_BRANCH}"
  build-ws:
    working_directory: ~/project
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/zweb-builder-backend-ws.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /zweb-builder-backend-ws.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=zweb-builder-backend-ws -f zweb-builder-backend-websocket.dockerfile -t zweb-builder-backend-ws .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/zweb-builder-backend-ws.tar zweb-builder-backend-ws
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/zweb-builder-backend-ws.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker tag zweb-builder-backend-ws "zwebsoft/zweb-builder-backend-ws:${CIRCLE_BRANCH}"
            docker push "zwebsoft/zweb-builder-backend-ws:${CIRCLE_BRANCH}"
  build-internal:
    working_directory: ~/project
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/zweb-builder-backend-internal.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /zweb-builder-backend-internal.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=zweb-builder-backend-internal -f zweb-builder-backend-internal.dockerfile -t zweb-builder-backend-internal .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/zweb-builder-backend-internal.tar zweb-builder-backend-internal
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/zweb-builder-backend-internal.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker tag zweb-builder-backend-internal "zwebsoft/zweb-builder-backend-internal:${CIRCLE_BRANCH}"
            docker push "zwebsoft/zweb-builder-backend-internal:${CIRCLE_BRANCH}"
  deploy:
    machine: # executor type
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - run:
          name: Download doctl & kubectl
          command: |
            sudo snap install doctl
            sudo snap install kubectl --classic
            doctl version
      - run:
          name: Setup kubectl
          command: |
            doctl auth init --access-token $DO_TOKEN
            mkdir -p /home/circleci/.kube
            sudo snap connect doctl:kube-config
            doctl kubernetes cluster kubeconfig save $DO_CLUSTER
            kubectl version
      - run:
          name: Download deployment configs
          command: |
            git clone $DEPLOY_REPO
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              echo "Deploying for main branch"
              echo "export NS=production" >> "$BASH_ENV"
              echo "export CFG_DIR=${DEPLOY_PRO_DIR}" >> "$BASH_ENV"
            elif [ "${CIRCLE_BRANCH}" = "beta" ]; then
              echo "Deploying for beta branch"
              echo "export NS=beta" >> "$BASH_ENV"
              echo "export CFG_DIR=${DEPLOY_BETA_DIR}" >> "$BASH_ENV"
            elif [ "${CIRCLE_BRANCH}" = "develop" ]; then
              echo "Deploying for develop branch"
              echo "export NS=test" >> "$BASH_ENV"
              echo "export CFG_DIR=${DEPLOY_TEST_DIR}" >> "$BASH_ENV"
            else
              echo "Not a deployable branch"
            fi
      - run:
          name: Deploy different branches
          command: |
            echo "Deploying to ${NS} namespace"
            cd ${CFG_DIR}
            pwd
            kubectl delete pod -n ${NS} -l repo=zweb-builder-backend
            kubectl delete pod -n ${NS} -l repo=zweb-builder-backend-ws
            kubectl delete pod -n ${NS} -l repo=zweb-builder-backend-internal
            kubectl apply -f ./zweb-builder-backend/ -n ${NS}
            kubectl apply -f ./zweb-builder-backend-ws/ -n ${NS}
            kubectl apply -f ./zweb-builder-backend-internal/ -n ${NS}

  build-all-in-one-image:
    parameters: # parameters are at the job level
      TAG:
        type: boolean
        default: false
    machine: # executor type
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run:
          name: Preprocess
          command: |
            if [ << parameters.TAG >> = true ]; then
              echo ${CIRCLE_TAG}
              echo "export IMAGE_TAG=${CIRCLE_TAG}" >> "$BASH_ENV"
              echo "export FE=main" >> "$BASH_ENV"
              echo "export BE=${CIRCLE_TAG}" >> "$BASH_ENV"
              echo "export SBE=main" >> "$BASH_ENV"
            else
              echo ${CIRCLE_BRANCH}
              echo "export IMAGE_TAG=${CIRCLE_BRANCH}" >> "$BASH_ENV"
              echo "export FE=${CIRCLE_BRANCH}" >> "$BASH_ENV"
              echo "export BE=${CIRCLE_BRANCH}" >> "$BASH_ENV"
              echo "export SBE=${CIRCLE_BRANCH}" >> "$BASH_ENV"
            fi
      - run:
          name: Download build scripts
          command: |
            git clone https://github.com/zilliangroup/build-all-in-one-image
      - run:
          name: Build and push Docker image
          command: |
            cd ./build-all-in-one-image
            docker build -f ./dockerfile -t zwebsoft/zweb-builder:${IMAGE_TAG} --build-arg FE=${FE} --build-arg BE=${BE} --build-arg SBE=${SBE} --no-cache .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push zwebsoft/zweb-builder:${IMAGE_TAG}
            if [ << parameters.TAG >> = true ]; then
              docker tag zwebsoft/zweb-builder:${IMAGE_TAG} zwebsoft/zweb-builder:latest
              docker push zwebsoft/zweb-builder:latest
            fi

workflows:
  zweb-builder-backend:
    when:
      or:
        - equal: [main, << pipeline.git.branch >>]
        - equal: [beta, << pipeline.git.branch >>]
        - equal: [develop, << pipeline.git.branch >>]
    jobs:
      - build:
          context:
            - org-global
      - build-ws:
          context:
            - org-global
      - build-internal:
          context:
            - org-global
      - deploy:
          context:
            - org-global
          requires:
            - build
            - build-ws
            - build-internal
  branch-build-all-in-one-image:
    when:
      or:
        - equal: [ main, << pipeline.git.branch >> ]
        - equal: [develop, << pipeline.git.branch >>]
    jobs:
      - build-all-in-one-image:
          context:
            - org-global
  tag-build-all-in-one-image:
    jobs:
      - build-all-in-one-image:
          context:
            - org-global
          TAG: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9].*/
